add checks for successful build

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -276,8 +276,12 @@ jobs:
               cd cbioportal-test
               export DOCKER_TAG=$CIRCLE_SHA1
               ./scripts/build-push-image.sh --src=/tmp/repos/cbioportal --push=true
-              EXISTS=$(docker manifest inspect $DOCKER_REPO:$DOCKER_TAG > /dev/null; echo $?)
-              exit $EXISTS
+              EXISTS=$(docker manifest inspect $DOCKER_REPO:$DOCKER_TAG-web-shenandoah > /dev/null; echo $?)
+              if [ $EXISTS -eq 0 ]; then
+                echo "Build succeeded!"
+              else
+                echo "Build failed!"
+                exit 1
 
     run_api_tests:
       machine:
