doesnt workd

diff --git a/.github/workflows/cbioportal-performance-test.yml b/.github/workflows/cbioportal-performance-test.yml
--- a/.github/workflows/cbioportal-performance-test.yml
+++ b/.github/workflows/cbioportal-performance-test.yml
@@ -54,7 +54,17 @@ jobs:
           EMPTY_LIST_RESPONSE: "[]"
           SEARCH_STR: "sampleId"
         run: |
-          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{studyIds: [\"msk_impact_2017\"]}'" > curl.out
+          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{\"studyIds\": [ \"msk_impact_2017\" ]}'" > curl.out 
+          head -1 curl.out | jq --join-output --compact-output '{sampleIdentifiers: [.[]|{sampleId: ."sampleId", studyId: "msk_impact_2017"}]}' > post_body.txt
+      - name: POST Request for cna-genes endpoint
+        env:
+          MAX_WAIT_TIME_IN_SECONDS: 180
+          URL: "http://localhost:8888/api/cna-genes/fetch"
+          OK_RESPONSE_CODE: 200
+          EMPTY_LIST_RESPONSE: "[]"
+          SEARCH_STR: "sampleId"
+        run: |
+          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --http1.1 --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '@post_body.txt'" > curl.out
           RESPONSE_CODE=`tail -1 curl.out`
           RESPONSE_BODY=`head -1 curl.out`
           if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
@@ -65,13 +75,30 @@ jobs:
                 echo "Request failed with empty response"
                 exit 1
             else
-                if [[ "$RESPONSE_BODY" != *"$SEARCH_STR"* ]]; then
-                    echo "Response did not contain search string '$SEARCH_STR'"
-                    exit 1
-                fi
+                echo "success"
+                echo "$RESPONSE_BODY"
             fi
             exit 0
           fi
+          
+
+#          RESPONSE_CODE=`tail -1 curl.out`
+#          RESPONSE_BODY=`head -1 curl.out`
+#          if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
+#            echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
+#            exit 1
+#          else
+#            if [ "$RESPONSE_BODY" == "$EMPTY_LIST_RESPONSE" ] || [ -z "$RESPONSE_BODY" ]; then 
+#                echo "Request failed with empty response"
+#                exit 1
+#            else
+#                if [[ "$RESPONSE_BODY" != *"$SEARCH_STR"* ]]; then
+#                    echo "Response did not contain search string '$SEARCH_STR'"
+#                    exit 1
+#                fi
+#            fi
+#            exit 0
+#          fi
       - name: POST Request for /clinical-data-bin-counts endpoint
         env:
           MAX_WAIT_TIME_IN_SECONDS: 180
