added another test which takes an array of samples as input instead of sampleIdentifiers

diff --git a/.github/workflows/cbioportal-performance-test.yml b/.github/workflows/cbioportal-performance-test.yml
--- a/.github/workflows/cbioportal-performance-test.yml
+++ b/.github/workflows/cbioportal-performance-test.yml
@@ -51,7 +51,7 @@ jobs:
           MAX_WAIT_TIME_IN_SECONDS: 180
           URL: "http://localhost:8888/api/filtered-samples/fetch"
         run: |
-          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{\"studyIds\": [ \"msk_impact_2017\" ]}' | jq --join-output --compact-output '{sampleIdentifiers: [.[]|{sampleId: .\"sampleId\", studyId: \"msk_impact_2017\"}]}' > sampleIdentifiers.json"
+          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{\"studyIds\": [ \"msk_impact_2017\" ]}' | jq --join-output --compact-output '[.[]|{sampleId: .\"sampleId\", studyId: \"msk_impact_2017\"}]' > samples.json; jq --join-output --compact-output '{sampleIdentifiers: [.[]]}' > sampleIdentifiers.json"
       - name: POST Request for /cna-genes endpoint
         env:
           MAX_WAIT_TIME_IN_SECONDS: 180
@@ -139,6 +139,32 @@ jobs:
           SEARCH_STR: "entrezGeneIdXXX"
         run: |
           kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '@sampleIdentifiers.json'" > curl.out
+          RESPONSE_CODE=`tail -1 curl.out`
+          RESPONSE_BODY=`head -1 curl.out`
+          if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
+            echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
+            exit 1
+          else
+            if [ "$RESPONSE_BODY" == "$EMPTY_LIST_RESPONSE" ] || [ -z "$RESPONSE_BODY" ]; then 
+                echo "Request failed with empty response"
+                exit 1
+            else
+                if [[ "$RESPONSE_BODY" != *"$SEARCH_STR"* ]]; then
+                    echo "Response did not contain search string '$SEARCH_STR'"
+                    exit 1
+                fi
+            fi
+            exit 0
+          fi
+      - name: POST Request for /copy-number-segments/fetch endpoint
+        env:
+          MAX_WAIT_TIME_IN_SECONDS: 180
+          URL: "http://localhost:8888/api/copy-number-segments/fetch?projection=META"
+          OK_RESPONSE_CODE: 200
+          EMPTY_LIST_RESPONSE: "[]"
+          SEARCH_STR: "blah"
+        run: |
+          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '@samples.json'" > curl.out
           RESPONSE_CODE=`tail -1 curl.out`
           RESPONSE_BODY=`head -1 curl.out`
           if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
