added more tests

diff --git a/.github/workflows/cbioportal-performance-test.yml b/.github/workflows/cbioportal-performance-test.yml
--- a/.github/workflows/cbioportal-performance-test.yml
+++ b/.github/workflows/cbioportal-performance-test.yml
@@ -51,8 +51,8 @@ jobs:
           MAX_WAIT_TIME_IN_SECONDS: 180
           URL: "http://localhost:8888/api/filtered-samples/fetch"
         run: |
-          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{\"studyIds\": [ \"msk_impact_2017\" ]}' | jq --join-output --compact-output '{sampleIdentifiers: [.[]|{sampleId: .\"sampleId\", studyId: \"msk_impact_2017\"}]}' > samples.json"
-      - name: POST Request for cna-genes endpoint
+          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{\"studyIds\": [ \"msk_impact_2017\" ]}' | jq --join-output --compact-output '{sampleIdentifiers: [.[]|{sampleId: .\"sampleId\", studyId: \"msk_impact_2017\"}]}' > sampleIdentifiers.json"
+      - name: POST Request for /cna-genes endpoint
         env:
           MAX_WAIT_TIME_IN_SECONDS: 180
           URL: "http://localhost:8888/api/cna-genes/fetch"
@@ -60,7 +60,85 @@ jobs:
           EMPTY_LIST_RESPONSE: "[]"
           SEARCH_STR: "entrezGeneId"
         run: |
-          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '@samples.json'" > curl.out
+          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '@sampleIdentifiers.json'" > curl.out
+          RESPONSE_CODE=`tail -1 curl.out`
+          RESPONSE_BODY=`head -1 curl.out`
+          if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
+            echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
+            exit 1
+          else
+            if [ "$RESPONSE_BODY" == "$EMPTY_LIST_RESPONSE" ] || [ -z "$RESPONSE_BODY" ]; then 
+                echo "Request failed with empty response"
+                exit 1
+            else
+                if [[ "$RESPONSE_BODY" != *"$SEARCH_STR"* ]]; then
+                    echo "Response did not contain search string '$SEARCH_STR'"
+                    exit 1
+                fi
+            fi
+            exit 0
+          fi
+      - name: POST Request for /treatments/patient endpoint
+        env:
+          MAX_WAIT_TIME_IN_SECONDS: 180
+          URL: "http://localhost:8888/api/treatments/patient"
+          OK_RESPONSE_CODE: 200
+          EMPTY_LIST_RESPONSE: "[]"
+          SEARCH_STR: "treatmentXXX"
+        run: |
+          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '@sampleIdentifiers.json'" > curl.out
+          RESPONSE_CODE=`tail -1 curl.out`
+          RESPONSE_BODY=`head -1 curl.out`
+          if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
+            echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
+            exit 1
+          else
+            if [ "$RESPONSE_BODY" == "$EMPTY_LIST_RESPONSE" ] || [ -z "$RESPONSE_BODY" ]; then 
+                echo "Request failed with empty response"
+                exit 1
+            else
+                if [[ "$RESPONSE_BODY" != *"$SEARCH_STR"* ]]; then
+                    echo "Response did not contain search string '$SEARCH_STR'"
+                    exit 1
+                fi
+            fi
+            exit 0
+          fi
+      - name: POST Request for /treatments/sample endpoint
+        env:
+          MAX_WAIT_TIME_IN_SECONDS: 180
+          URL: "http://localhost:8888/api/treatments/sample"
+          OK_RESPONSE_CODE: 200
+          EMPTY_LIST_RESPONSE: "[]"
+          SEARCH_STR: "treatmentXXX"
+        run: |
+          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '@sampleIdentifiers.json'" > curl.out
+          RESPONSE_CODE=`tail -1 curl.out`
+          RESPONSE_BODY=`head -1 curl.out`
+          if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
+            echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
+            exit 1
+          else
+            if [ "$RESPONSE_BODY" == "$EMPTY_LIST_RESPONSE" ] || [ -z "$RESPONSE_BODY" ]; then 
+                echo "Request failed with empty response"
+                exit 1
+            else
+                if [[ "$RESPONSE_BODY" != *"$SEARCH_STR"* ]]; then
+                    echo "Response did not contain search string '$SEARCH_STR'"
+                    exit 1
+                fi
+            fi
+            exit 0
+          fi
+      - name: POST Request for /fusion-genes/fetch endpoint
+        env:
+          MAX_WAIT_TIME_IN_SECONDS: 180
+          URL: "http://localhost:8888/api/fusion-genes/fetch"
+          OK_RESPONSE_CODE: 200
+          EMPTY_LIST_RESPONSE: "[]"
+          SEARCH_STR: "entrezGeneIdXXX"
+        run: |
+          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '@sampleIdentifiers.json'" > curl.out
           RESPONSE_CODE=`tail -1 curl.out`
           RESPONSE_BODY=`head -1 curl.out`
           if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
@@ -130,32 +208,32 @@ jobs:
             fi
             exit 0
           fi
-#      - name: POST Request for /clinical-data-density-plot endpoint
-#        env:
-#          MAX_WAIT_TIME_IN_SECONDS: 180
-#          URL: "http://localhost:8888/api/clinical-data-density-plot/fetch?xAxisAttributeId=FRACTION_GENOME_ALTERED&xAxisBinCount=50&xAxisEnd=1&xAxisStart=0&yAxisAttributeId=MUTATION_COUNT&yAxisBinCount=52&yAxisStart=0"
-#          OK_RESPONSE_CODE: 200
-#          EMPTY_LIST_RESPONSE: "[]"
-#          SEARCH_STR: "SAMPLE_COUNT"
-#        run: |
-#          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '@clinical-data-density-plot.txt'" > curl.out
-#          RESPONSE_CODE=`tail -1 curl.out`
-#          RESPONSE_BODY=`head -1 curl.out`
-#          if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
-#            echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
-#            exit 1
-#          else
-#            if [ "$RESPONSE_BODY" == "$EMPTY_LIST_RESPONSE" ] || [ -z "$RESPONSE_BODY" ]; then 
-#                echo "Request failed with empty response"
-#                exit 1
-#            else
-#                if [[ "$RESPONSE_BODY" != *"$SEARCH_STR"* ]]; then
-#                    echo "Response did not contain search string '$SEARCH_STR'"
-#                    exit 1
-#                fi
-#            fi
-#            exit 0
-#          fi
+      - name: POST Request for /clinical-data-density-plot endpoint
+        env:
+          MAX_WAIT_TIME_IN_SECONDS: 180
+          URL: "http://localhost:8888/api/clinical-data-density-plot/fetch?xAxisAttributeId=FRACTION_GENOME_ALTERED&xAxisBinCount=50&xAxisEnd=1&xAxisStart=0&yAxisAttributeId=MUTATION_COUNT&yAxisBinCount=52&yAxisStart=0"
+          OK_RESPONSE_CODE: 200
+          EMPTY_LIST_RESPONSE: "[]"
+          SEARCH_STR: "SAMPLE_COUNT"
+        run: |
+          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '@sampleIdentifiers.json'" > curl.out
+          RESPONSE_CODE=`tail -1 curl.out`
+          RESPONSE_BODY=`head -1 curl.out`
+          if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
+            echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
+            exit 1
+          else
+            if [ "$RESPONSE_BODY" == "$EMPTY_LIST_RESPONSE" ] || [ -z "$RESPONSE_BODY" ]; then 
+                echo "Request failed with empty response"
+                exit 1
+            else
+                if [[ "$RESPONSE_BODY" != *"$SEARCH_STR"* ]]; then
+                    echo "Response did not contain search string '$SEARCH_STR'"
+                    exit 1
+                fi
+            fi
+            exit 0
+          fi
       - name: POST Request for /mutated-genes endpoint
         env:
           MAX_WAIT_TIME_IN_SECONDS: 180 
