expand tests

diff --git a/.github/workflows/cbioportal-performance-test.yml b/.github/workflows/cbioportal-performance-test.yml
--- a/.github/workflows/cbioportal-performance-test.yml
+++ b/.github/workflows/cbioportal-performance-test.yml
@@ -48,11 +48,11 @@ jobs:
             kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "apt-get update; apt-get -y install curl"
       - name: POST Request for /clinical-data-bin-counts endpoint
         env:
-          MAX_WAIT_TIME_IN_SECONDS: 300
-          URL: "http://localhost:8888/api/clinical-data-bin-counts/fetch"
+          MAX_WAIT_TIME_IN_SECONDS: 180
+          URL: "http://localhost:8888/api/clinical-data-bin-counts/fetch?dataBinMethod=STATIC"
           OK_RESPONSE_CODE: 200
           EMPTY_LIST_RESPONSE: "[]"
-          SEARCH_STR: "MUTATION_COUNTXXX"
+          SEARCH_STR: "MUTATION_COUNT"
         run: |
           kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{\"attributes\":[{\"attributeId\":\"MUTATION_COUNT\",\"disableLogScale\":false},{\"attributeId\":\"FRACTION_GENOME_ALTERED\",\"disableLogScale\":false},{\"attributeId\":\"AGE_AT_SEQ_REPORT\",\"disableLogScale\":false},{\"attributeId\":\"AGE_AT_SEQ_REPORT_DAYS\",\"disableLogScale\":false},{\"attributeId\":\"INT_CONTACT\",\"disableLogScale\":false},{\"attributeId\":\"INT_DOD\",\"disableLogScale\":false},{\"attributeId\":\"SEQ_YEAR\",\"disableLogScale\":false}],\"studyViewFilter\":{\"studyIds\":[\"msk_impact_2017\"],\"patientTreatmentFilters\":{\"filters\":[]},\"sampleTreatmentFilters\":{\"filters\":[]}}}'" > curl.out
           RESPONSE_CODE=`tail -1 curl.out`
@@ -74,11 +74,11 @@ jobs:
           fi
       - name: POST Request for /clinical-data-counts endpoint
         env:
-          MAX_WAIT_TIME_IN_SECONDS: 300
+          MAX_WAIT_TIME_IN_SECONDS: 180
           URL: "http://localhost:8888/api/clinical-data-counts/fetch"
           OK_RESPONSE_CODE: 200
           EMPTY_LIST_RESPONSE: "[]"
-          SEARCH_STR: "SAMPLE_COUNTXXX"
+          SEARCH_STR: "SAMPLE_COUNT"
         run: |
           kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{\"attributes\":[{\"attributeId\":\"CANCER_TYPE\"},{\"attributeId\":\"CANCER_TYPE_DETAILED\"},{\"attributeId\":\"SAMPLE_COUNT\"},{\"attributeId\":\"SEX\"},{\"attributeId\":\"ETHNICITY\"},{\"attributeId\":\"SAMPLE_TYPE\"},{\"attributeId\":\"CENTER\"},{\"attributeId\":\"ONCOTREE_CODE\"},{\"attributeId\":\"PRIMARY_RACE\"},{\"attributeId\":\"SAMPLE_TYPE_DETAILED\"},{\"attributeId\":\"SECONDARY_RACE\"},{\"attributeId\":\"SEQ_ASSAY_ID\"},{\"attributeId\":\"TERTIARY_RACE\"}],\"studyViewFilter\":{\"studyIds\":[\"msk_impact_2017\"],\"patientTreatmentFilters\":{\"filters\":[]},\"sampleTreatmentFilters\":{\"filters\":[]}}}'" > curl.out
           RESPONSE_CODE=`tail -1 curl.out`
@@ -98,13 +98,39 @@ jobs:
             fi
             exit 0
           fi
+#      - name: POST Request for /clinical-data-density-plot endpoint
+#        env:
+#          MAX_WAIT_TIME_IN_SECONDS: 180
+#          URL: "http://localhost:8888/api/clinical-data-density-plot/fetch?xAxisAttributeId=FRACTION_GENOME_ALTERED&xAxisBinCount=50&xAxisEnd=1&xAxisStart=0&yAxisAttributeId=MUTATION_COUNT&yAxisBinCount=52&yAxisStart=0"
+#          OK_RESPONSE_CODE: 200
+#          EMPTY_LIST_RESPONSE: "[]"
+#          SEARCH_STR: "SAMPLE_COUNT"
+#        run: |
+#          kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '@clinical-data-density-plot.txt'" > curl.out
+#          RESPONSE_CODE=`tail -1 curl.out`
+#          RESPONSE_BODY=`head -1 curl.out`
+#          if [ "$RESPONSE_CODE" != "$OK_RESPONSE_CODE" ]; then
+#            echo "Request failed with response code '$RESPONSE_CODE', expected '$OK_RESPONSE_CODE'"
+#            exit 1
+#          else
+#            if [ "$RESPONSE_BODY" == "$EMPTY_LIST_RESPONSE" ] || [ -z "$RESPONSE_BODY" ]; then 
+#                echo "Request failed with empty response"
+#                exit 1
+#            else
+#                if [[ "$RESPONSE_BODY" != *"$SEARCH_STR"* ]]; then
+#                    echo "Response did not contain search string '$SEARCH_STR'"
+#                    exit 1
+#                fi
+#            fi
+#            exit 0
+#          fi
       - name: POST Request for /mutated-genes endpoint
         env:
-          MAX_WAIT_TIME_IN_SECONDS: 300
+          MAX_WAIT_TIME_IN_SECONDS: 180 
           URL: "http://localhost:8888/api/mutated-genes/fetch"
           OK_RESPONSE_CODE: 200
           EMPTY_LIST_RESPONSE: "[]"
-          SEARCH_STR: "entrezGeneIdXXX"
+          SEARCH_STR: "entrezGeneId"
         run: |
           kubectl exec -it ${{ steps.extract_pod_name.outputs.pod_name }} -- bash -c "curl --max-time $MAX_WAIT_TIME_IN_SECONDS -s -w '\n\n%{http_code}' -X POST '$URL' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{\"studyIds\": [ \"msk_impact_2017\" ]}'" > curl.out
           RESPONSE_CODE=`tail -1 curl.out`
@@ -131,7 +157,7 @@ jobs:
       - name: DELETE request to dockerhub
         if: ${{ always() }}
         env:
-          MAX_WAIT_TIME_IN_SECONDS: 300
+          MAX_WAIT_TIME_IN_SECONDS: 180
           URL: "https://hub.docker.com/v2/repositories/cbioportalpipelines/cbioportal/tags/${{ steps.extract_tags.outputs.image_tag }}/"
           OK_RESPONSE_CODE: 204
 
