Update genie-performance-test.yml (#11)

diff --git a/.github/workflows/genie-performance-test.yml b/.github/workflows/genie-performance-test.yml
--- a/.github/workflows/genie-performance-test.yml
+++ b/.github/workflows/genie-performance-test.yml
@@ -15,10 +15,21 @@ jobs:
     - name: GET request to genie private page
       env:
         GENIE_PRIVATE_SECRET: ${{ secrets.GENIE_PRIVATE_SECRET }}
+        MAX_WAIT_TIME_IN_SECONDS: 0.001
+        URL: "https://genie.cbioportal.org/api/studies/genie_public"
+      # GET request to genie private with a 1 second limit (TODO UPDATE)
+      #   if curl fails, exit with non-zero exit code
+      #   else if we did not get a 200 response code exit with a non-zero exit code
+      #   else we are OK!
       run: |
-        curl -I -H "Authorization:Bearer $GENIE_PRIVATE_SECRETBLAH" "https://genie.cbioportal.org/api/studies/genie_public" -H "accept:application/json" | head -1 | cut -d" " -f2
-        if [ "$RESPONSE_CODE" == "200" ]; then
+        curl --max-time $MAX_WAIT_TIME_IN_SECONDS -I -H "Authorization:Bearer $GENIE_PRIVATE_SECRET" "$URL" -H "accept:application/json" > curl.out
+        if [ $? -ne 0 ]; then
+          echo "Curl failed, exiting..."
+          exit 1
+        fi
+        RESPONSE_CODE=`head -1 curl.out | cut -d" " -f2`
+        if [ "$RESPONSE_CODE" != "200" ]; then
           exit 0
         else 
-          echo 1
+          exit 1
         fi
